context: 'Adult population (18+) in the United States in 2018.

  '
population_context:
  reference_year: 2018
input_variables:
  birth_year:
    type: static
    description: Year of birth
    domain: Demography
    allowed:
      type: numeric
      min: 1929
      max: 2000
  age:
    type: static
    description: Age
    domain: Demography
    allowed:
      type: numeric
      min: 18
      max: 89
  gender:
    type: static
    description: Sex
    domain: Demography
    allowed:
    - Female
    - Male
  race:
    type: static
    description: Racial/ethnic identification
    domain: Demography
    allowed:
    - Black
    - Hispanic
    - Non-Black, Non-Hispanic
  immigrant_status:
    type: static
    description: Immigration status
    domain: Demography
    allowed:
    - Non-immigrant
    - Immigrant
  mother_education:
    type: static
    description: Mother's educational attainment
    domain: Demography
    allowed:
    - Less than high school
    - High school
    - College and above
  father_education:
    type: static
    description: Father's educational attainment
    domain: Demography
    allowed:
    - Less than high school
    - High school
    - College and above
  mother_occupation:
    type: static
    description: Mother's occupation
    domain: Demography
    allowed:
    - Management, professional, and related occupations
    - Service occupations
    - Sales and office occupations
    - Natural resources, construction, and maintenance occupations
    - Production, transportation, and material moving occupations
    - Military Occupations
  father_occupation:
    type: static
    description: Father's occupation
    domain: Demography
    allowed:
    - Management, professional, and related occupations
    - Service occupations
    - Sales and office occupations
    - Natural resources, construction, and maintenance occupations
    - Production, transportation, and material moving occupations
    - Military Occupations
output_variables:
  marital_status:
    type: static
    description: Marital status
    domain: Marriage
    allowed:
    - Married
    - Divorced/widowed
    - Single
  child_number:
    type: static
    description: Number of Child ever born
    domain: Marriage
    allowed:
      type: numeric
      min: 0
      max: 8
  age_first_childbirth:
    type: static
    description: Age at first childbirth
    domain: Marriage
    allowed:
      type: numeric
      min: 17
      max: 45
      special:
      - No Child
  education:
    type: static
    description: Educational attainment
    domain: SES
    allowed:
    - Less than high school
    - High school
    - College and above
  laborforce:
    type: static
    description: Whether the respondent participated in the labor force
    domain: SES
    allowed:
    - Not in the labor force
    - In the labor force
  occupation:
    type: static
    description: Occupation
    domain: SES
    allowed:
    - Management, professional, and related occupations
    - Service occupations
    - Sales and office occupations
    - Natural resources, construction, and maintenance occupations
    - Production, transportation, and material moving occupations
    - Military Occupations
    - Unemployed
  spouse_occupation:
    type: static
    description: Spouse's occupation
    domain: SES
    allowed:
    - Management, professional, and related occupations
    - Service occupations
    - Sales and office occupations
    - Natural resources, construction, and maintenance occupations
    - Production, transportation, and material moving occupations
    - Military Occupations
    - No spouse
  income:
    type: static
    description: Income from occupation last year
    domain: SES
    allowed:
    - LT $5000
    - $5000 TO 9999
    - $10000 OR MORE
    - Unemployed
  wealth:
    type: static
    description: Total personal wealth
    domain: SES
    allowed:
    - LT $40000
    - $40000 TO 500000
    - More than $500000
  health:
    type: static
    description: Self-evaluated health condition
    domain: Health
    allowed:
    - Excellent
    - Good
    - Fair
    - Poor
  depress:
    type: static
    description: Ever had depression or not
    domain: Health
    allowed:
    - Had depression
    - No depression
  isolated:
    type: static
    description: how often in the past 4 weeks has felt isolated from others
    domain: Health
    allowed:
    - Never
    - Rarely
    - Sometimes
    - Often
    - Very often
  lonely:
    type: static
    description: how often in the past 4 weeks has felt that lack companionship
    domain: Health
    allowed:
    - Never
    - Rarely
    - Sometimes
    - Often
    - Very often
  mental_health:
    type: static
    description: how many days during the past 30 days was mental health condition not good
    domain: Health
    allowed:
      type: numeric
      min: 0
      max: 30
  gender_role_attitude:
    type: static
    description: Attitude toward gender roles, indicated by agreeing or disagreeing the sentence "It is
      much better for everyone involved if the man is the achiever outside the home and the woman takes
      care of the home and family."
    domain: Attitude
    allowed:
    - Agree
    - Disagree
  happy:
    type: static
    description: General happiness
    domain: Attitude
    allowed:
    - Very happy
    - Pretty happy
    - Not too happy
  political_view:
    type: static
    description: Political view
    domain: Attitude
    allowed:
    - Liberal
    - Middle
    - Conservative
  satisfy_job:
    type: static
    description: Satisfaction with work
    domain: Attitude
    allowed:
    - Very satisfied
    - Moderately satisfied
    - A little dissatisfied
    - Very dissatisfied
  trust:
    type: static
    description: Trust with people
    domain: Attitude
    allowed:
    - Most people can be trusted
    - Can't be too careful
    - Depends
  vocabulary_test:
    type: static
    description: Total number of correct words in a vocabulary test, which is an indicator of the level
      of cognitive skills
    domain: Ability
    allowed:
      type: numeric
      min: 0
      max: 10
  work_hard:
    type: static
    description: Evaluation on the importance of working hard, which is an indicator of the level of noncognitive
      skills
    domain: Ability
    allowed:
    - MOST IMPORTANT
    - 2ND IMPORTANT
    - 3RD IMPORTANT
    - 4TH IMPORTANT
    - LEAST IMPORTANT
preprocessing:
  source: data/real_data/gss/gss2018.csv
  drop_first_column: true
  require_complete_inputs: false
